apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: grafanet
    url: http://mimir:9009/prometheus
    isDefault: true
  - name: Loki
    type: loki
    access: grafanet
    url: http://loki:3100
  - name: Tempo
    type: tempo
    access: grafanet
    url: http://tempo:3200
    serviceMap:
      datasourceUid: 'Mimir'
