apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  labels:
    app: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:latest
          args:
            - "-target=all"
            - "--config.file=/etc/mimir-config.yaml"
          ports:
            - containerPort: 9009
          volumeMounts:
            - name: mimir-config
              mountPath: /etc/mimir-config.yaml
              subPath: mimir-config.yaml
      volumes:
        - name: mimir-config
          configMap:
            name: mimir-config