apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    # ✅ แก้ไข URL ให้ตรงกับ port ของ Mimir
    url: http://mimir:9009/prometheus
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    serviceMap:
      datasourceUid: 'Mimir' # ✅ บอกให้ Tempo ใช้ Mimir สำหรับ Service Graph