apiVersion: v1
kind: Service
metadata:
  name: alloy
spec:
  type: ClusterIP
  selector:
    app: alloy
  ports:
    - name: http
      protocol: TCP
      port: 12345
      targetPort: 12345
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318