apiVersion: v1
kind: Service
metadata:
  name: observability
spec:
  type: LoadBalancer
  selector:
    app: observability
  ports:
    - name: app
      port: 8080
      targetPort: 8080
    - name: otlp
      port: 4318
      targetPort: 4318