networks:
  grafanet:
    external: true

services:
  # --- Observability Backend ---
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: "-config.file=/etc/loki/local-config.yaml"
    networks:
      - grafanet
  tempo:
    image: grafana/tempo:latest
    command: ["-target=all", "-storage.trace.backend=local", "-storage.trace.local.path=/tmp/tempo", "-auth.enabled=false", "-server.http-listen-port=3200"]
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
    networks:
      - grafanet
  mimir:
    image: grafana/mimir:2.16.0
    command: ["-target=all", "-auth.multitenancy-enabled=false", "-server.http-listen-port=9009"]
    ports:
      - "9009:9009"
    networks:
      - grafanet
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - loki
      - tempo
      - mimir
    networks:
      - grafanet

