networks:
  grafanet:
    external: true

services:
  # --- Observability Backend ---
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: "-config.file=/etc/loki/local-config.yaml"
    networks:
      - grafanet
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      # - "14268:14268" # jaeger ingest
      - "3200:3200" # tempo
      # - "9095:9095" # tempo grpc
      # - "4317:4317" # otlp grpc
      # - "4318:4318" # otlp http
      # - "9411:9411" # zipkin
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
    networks:
      - grafanet
  mimir:
    image: grafana/mimir:2.16.0
    command: [-config.file=/etc/mimir.yaml]
    ports:
      - "9009:9009"
    volumes:
      - ./configs/mimir.yaml:/etc/mimir.yaml
    networks:
      - grafanet
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - loki
      - tempo
      - mimir
    networks:
      - grafanet

