networks:
  grafanet:
    external: true

services:
  # --- Observability Backend ---
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: "-config.file=/etc/loki/local-config.yaml"
    networks:
      - grafanet
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - loki
    networks:
      - grafanet